### ISSUE TITLE
An escape hatch for generating one off non-atomic classes

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#257] opened 2020-10-02 06:49 UTC
**Problem**
An external library we're using requires providing a `className` to it. It internally calls `someElement.classList.add(className)`.

When providing a `className` generated by stitches it errors out as `classList.add` api does not expect empty spaces in a class.

**Proposed Solution**
Provide an optional api that generates non-atomic classNames for such one off cases

```
myClass = css({}, atomic = false)
```

**Comment by peduarte** [comment] 2020-10-02 08:22
Hmm I'd like to understand this issue deeper. Which library is it, can you share? 

To clarify, it expects the class name to be string without any spaces in it:

"abc123" ✅
"abc123 def345" ❌

Is that correct? 

Regarding the suggested escape hatch: the entire structure of stitches is designed around atomic mindset. For stitches to generate a single class name containing all the CSS, I believe it would require a fair bit of work which would result in a larger bundle size, etc. I don't think itd be a "escape hatch" but rather an alternative approach to generate CSS altogether. 

But let's keep our options open until we understand the issue at hand fully

**Comment by afzalsayed96** [comment] 2020-10-02 09:13
> Hmm I'd like to understand this issue deeper. Which library is it, can you share?

I'm trying to integrate with [Muuri](https://github.com/haltu/muuri). It's not particularly a react library but it's working well so far. To be specific I'm trying to use it's `itemClass` [option](https://github.com/haltu/muuri#grid-option-itemclass)


> To clarify, it expects the class name to be string without any spaces in it:
>
>"abc123" ✅
>"abc123 def345" ❌

You are right except that the library doesn't expect class name to be that way, but the [dom api](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) `Element.classList.add` does (which Muuri calls internally)


>Regarding the suggested escape hatch: the entire structure of stitches is designed around atomic mindset. For stitches to generate a single class name containing all the CSS, I believe it would require a fair bit of work which would result in a larger bundle size, etc. I don't think itd be a "escape hatch" but rather an alternative approach to generate CSS altogether.

Ugh! I wouldn't like that either

I was hoping we could have an api similar to `css.global` to consolidate atomic classNames into one class

**Comment by peduarte** [comment] 2020-10-02 09:35
The `classList.add` API supports adding multiple classes, right? 

```
span.classList.add("d", "e", "f");
```

Is there any chance this is something that Muuri should handle infernally? 

Sorry if I'm asking dumb questions, just wanna make sure I'm understanding it right.

**Comment by afzalsayed96** [comment] 2020-10-02 09:48
That's a valid point. However, in this case `classList.add` is just an implementation detail. For the outside world, Muuri's options api expects a single className which I'm not able to provide with stitches.

Suppose Muuri decides to do `document.querySelector` with the provided className, then that would fail too with space separated classes.

**Comment by peduarte** [comment] 2020-10-02 10:04
Would it be too much to ask to provide a minimal reproducible example on codesandbox, please? 

Thanks!

**Comment by niklasramo** [comment] 2020-10-02 18:57
@afzalsayed96 Not sure if it's the solution you are looking for, but you can just provide empty strings to any of Muuri's className options. Muuri doesn't use the class names internally for anything.

**Comment by afzalsayed96** [comment] 2020-10-02 19:06
Hey @niklasramo , Thanks for chiming in. Actually I want to pass `options.itemPlaceholderClass`, `options.itemDraggingClass`, etc so I can style them.

I will create a minimal reproducible codesandbox example and share here.

**Comment by afzalsayed96** [comment] 2020-10-03 06:28
Reproducible example: https://codesandbox.io/s/quizzical-wind-0q6fe?file=/src/App.tsx
Try dragging one of the boxes to trigger error

**Comment by peduarte** [comment] 2020-10-05 08:53
@afzalsayed96 Got it. Yeah, I see what you mean.

Hmm, Muuri expects a classname, to add when the item is dragging. And Stitches doesn't return a single classname because it's atomic. So a bit of a clash in philosophies 😄 

Luckily, Stitches allows you to target descendants, and apply styles that way. 

With that being said, the way I would approach this would be to:

```js
// pass a string to Muuri
itemDraggingClass: "dragging",
```

```js
// target it in the muti item component via the descendant selector
const Box = styled("div", {
  "&.dragging": {
    backgroundColor: "$gray400",
  }
});
```

Demo: https://codesandbox.io/s/bold-violet-0jc9q?file=/src/App.tsx:209-390

---

How does that work for you?

**Comment by afzalsayed96** [comment] 2020-10-05 08:59
That would work for now. Thanks a lot!

**Comment by peduarte** [comment] 2020-10-05 09:27
Awesome. I'll close this, since generating OOCSS is not on the Stitches roadmap, at least for now. Thank you <3

**Closed by peduarte** 2020-10-05 09:27 UTC
