### ISSUE TITLE
Typescript sees props as part of stitches api

### ISSUE THREAD

**Issue by Preshonyee** [modulz/stitches#219] opened 2020-09-17 04:30 UTC
# Bug report
TypeScript is seeing my component props as part of the stitches responsive API

## Describe the bug
When I define my component props, typescript somehow is seeing it as the props from the Stitches responsive API and wouldn't let me proceed.

## To Reproduce
![image](https://user-images.githubusercontent.com/19210093/93419845-c1076100-f8a5-11ea-877b-af95de6af31c.png)

![image](https://user-images.githubusercontent.com/19210093/93419879-d5e3f480-f8a5-11ea-9e69-375629fda8c7.png)

![image](https://user-images.githubusercontent.com/19210093/93419970-fc099480-f8a5-11ea-9b28-d4518f88af18.png)

## Expected behavior

I should be able to go ahead and create my component without the `no overload matches this call` error message. Right now, the only way to bypass this is to pass `any` as the type to the component definition, but this is not what I want.

![image](https://user-images.githubusercontent.com/19210093/93420395-b5686a00-f8a6-11ea-8aa4-6415afeb051d.png)

## Screenshots
![image](https://user-images.githubusercontent.com/19210093/93419427-b8625b00-f8a4-11ea-8f89-a28f1f3b6dfd.png)

![image](https://user-images.githubusercontent.com/19210093/93419448-c6b07700-f8a4-11ea-8692-76f3dec572c8.png)

```jsx
No overload matches this call.
  Overload 1 of 2, '(props: Pick<DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>, "slot" | ... 253 more ... | "onTransitionEndCapture"> & { ...; } & { ...; } & VariantASProps<...>): any', gave the following error.
    Type '"tiny" | "small" | "large" | undefined' is not assignable to type '"small" | { mobile?: "small" | undefined; tablet?: "small" | undefined; laptop?: "small" | undefined; desktop?: "small" | undefined; initial?: "small" | undefined; } | undefined'.
      Type '"tiny"' is not assignable to type '"small" | { mobile?: "small" | undefined; tablet?: "small" | undefined; laptop?: "small" | undefined; desktop?: "small" | undefined; initial?: "small" | undefined; } | undefined'.
  Overload 2 of 2, '(props: ({ as: "symbol" | "object" | "body" | "small" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "br" | "button" | ... 157 more ... | FunctionComponent<...>; css?: (string & { ...; }) | ... 4 more ... | undefined; className?: string | undefined; children?: any; } & VariantASProps<...> & Pick<...> & { ...; }) | ... 123 more ... | ({ ...; } & ... 1 more ... & RefAttributes<...>)): any', gave the following error.
    Type '"tiny" | "small" | "large" | undefined' is not assignable to type '"small" | { mobile?: "small" | undefined; tablet?: "small" | undefined; laptop?: "small" | undefined; desktop?: "small" | undefined; initial?: "small" | undefined; } | ({ mobile?: "small" | undefined; tablet?: "small" | undefined; laptop?: "small" | undefined; desktop?: "small" | undefined; initial?: "small" | undef...'.
      Type '"tiny"' is not assignable to type '"small" | { mobile?: "small" | undefined; tablet?: "small" | undefined; laptop?: "small" | undefined; desktop?: "small" | undefined; initial?: "small" | undefined; } | ({ mobile?: "small" | undefined; tablet?: "small" | undefined; laptop?: "small" | undefined; desktop?: "small" | undefined; initial?: "small" | undef...'.ts(2769)
typography.tsx(29, 5): The expected type comes from property 'size' which is declared here on type 'IntrinsicAttributes & Pick<DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>, "slot" | ... 253 more ... | "onTransitionEndCapture"> & { ...; } & { ...; } & VariantASProps<...>'
typography.tsx(29, 5): The expected type comes from property 'size' which is declared here on type '(IntrinsicAttributes & { as: "symbol" | "object" | "body" | "small" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | ... 162 more ... | FunctionComponent<...>; css?: (string & { ...; }) | ... 4 more ... | undefined; className?: string | undefined; children?: any; } & Varia...'
;

```

## System information

- OS: macOS

**Comment by peduarte** [comment] 2020-09-17 12:21
@Preshonyee hey, thanks for raising this. I think I know what's going on 🙂 but before I jump to conclusions, can you create a minimal example with CodeSandbox, please?

Thanks!

**Comment by Preshonyee** [comment] 2020-09-17 20:08
> @Preshonyee hey, thanks for raising this. I think I know what's going on 🙂 but before I jump to conclusions, can you create a minimal example with CodeSandbox, please?
> 
> Thanks!

Here's a sample in CodeSandbox https://codesandbox.io/s/stitches-issue-sample-sccfd?file=/src/components/typography/typography.tsx

**Comment by afzalsayed96** [comment] 2020-09-19 12:06
Hey @Preshonyee, I was just going through this issue and have a few thoughts

- You've defined `size?: 'tiny' | 'small' | 'large';` in your `TypographyProps`
- But you have only defined one size variant in your `Display` component
```js
const Display = styled('h1', {
....
variants: {
    size: {
      // for small sized option
      small: {
        fontSize: '$displaySmall',
        letterSpacing: '$1',
      },
    },
}
```

Now `TypographyProps['size']` isn't compatible with `Display['size']` and in fact if you go ahead and define sizes `tiny` and `large`, it would work as expected.

```js
  variants: {
    size: {
      // for small sized option
      small: {
        fontSize: '$displaySmall',
        letterSpacing: '$1',
      },
      tiny: {},
      large: {},
    },
  }
```

Working sandbox: https://codesandbox.io/s/stitches-issue-sample-forked-3bhs9?file=/src/components/typography/typography.tsx:699-887

If you can confirm that my understanding is correct here then I'd say that this is intended behavior. You just need to be careful when redefining types for your variants.

**Comment by peduarte** [comment] 2020-09-23 18:19
@Preshonyee hey 👋 I think what @afzalsayed96 makes sense. Wanna give that a go and report back? Cheers!

**Comment by Preshonyee** [comment] 2020-09-26 08:58
@peduarte @afzalsayed96 I can confirm that this works correctly, but as @afzalsayed96 pointed out i'd have to define the `tiny`, `small` and `large` sizes for all components.

I only want the `small` size for the `Display` component while the `Heading` and `Body` components can have all three sizes `tiny`, `small` and `large`. This means that I have to still define the other two sizes for the `Display` components as empty objects for it to work. Is there any tradeoff with this?

<img width="437" alt="image" src="https://user-images.githubusercontent.com/19210093/94336776-873d0580-ffdd-11ea-9dc3-49226861cce0.png">

Another option would be to define a separate type definition for the `Display` component and make it's variant separate from the other components.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/19210093/94336836-092d2e80-ffde-11ea-8f90-00c058a4f3e6.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/19210093/94336862-3843a000-ffde-11ea-9772-6e7816d7735b.png">

I'm sorry for the delayed response, I've been out of work for some while.

**Comment by peduarte** [comment] 2020-09-28 12:37
@Preshonyee this doesn't seem to be an issue with Stitches, but more an abstraction issue 😄

**Comment by peduarte** [comment] 2020-09-30 10:17
@Preshonyee Im closing this based on the above, feel free to re-open if you wanna chat more. Cheers man!

**Closed by peduarte** 2020-09-30 10:17 UTC
