### ISSUE TITLE
Unexpected results when using `&` and comma separated pseudo selectors

### ISSUE THREAD

**Issue by mahaveer0496** [modulz/stitches#336] opened 2021-02-07 17:22 UTC
# Bug report

## Describe the bug
When using `&` at the top level, the selector doesn't target the current element.

these styles don't get applied at all
```
const Text = styled("span", {
  color: "red"
});

const Button = styled("button", {
  "&:hover, &:focus": { //<---
    [`& ${Text}`]: {
      color: "blue"
    }
  }
});
```
this gets applied to the root element
using comma-separated keys don't work either
```
const Button2 = styled("button", {
  ":hover": {
    [`& ${Text}`]: {
      color: "blue"
    }
  },
  ":focus": {
    [`& ${Text}`]: {
      color: "blue"
    }
  }
});
```

## To Reproduce
1. Go to https://codesandbox.io/s/stitches-bugs-n1hl3?file=/src/App.js
2. Hover/Focus on the first button

## Expected behavior
`&` should target the current element? If there's a special caveat when using `&` with stitches, can we know?

## Additional context
Here's a codesandbox but with `styled-components` which works as expected https://codesandbox.io/s/styled-components-forked-9kuqf?file=/index.js

**Comment by dsbrianwebster** [comment] 2021-02-09 03:46
Duplicate of #278

**Comment by peduarte** [comment] 2021-02-09 08:54
Thanks. Closing as it's duplicated. It's fixed in beta BTW, launching soon. Follow on Twitter for updates [@stitchesjs](https://twitter.com/stitchesjs)

**Closed by peduarte** 2021-02-09 08:54 UTC
