### ISSUE TITLE
Style precedence - all: 'unset' overrides subsequent styles

### ISSUE THREAD

**Issue by rafgraph** [modulz/stitches#315] opened 2020-12-02 23:30 UTC
# Bug report

## Describe the bug

Using `all: 'unset'` as first style unsets all subsequent styles.
Using `all: 'unset'` as last style works as intended (styles are first unset, and then additional styles added).

However, if `all: 'unset'` is used in a component, then it overrides styles in other components that use `all: 'unset'`.

## To Reproduce

See https://codesandbox.io/s/unset-button-vg40r-bpzt5?file=/src/App.tsx

## Expected behavior

Styles that appear later should take precedence, so using `all: 'unset'` as first style should work the same as css. Also, style precedence should respect the style's placement in each `styled` component.

## System information

- Version of Stitches: 0.0.3-canary.4

**Comment by peduarte** [comment] 2020-12-03 08:35
@rafgraph hey! Thanks for that. Well spotted 👁️ 

As you probably know, this is being caused by a CSS Specificity issue. The `all` property is being injected after the other properties so its overriding. 

Issues like this happen a lot as a result of generating Atomic CSS. Since only 1 CSS Rule is created per CSS Declaration.

With the new upcoming release of Stitches, issues like this will no longer exist. I'll be writing a blog post once its released with all details. 

In the meantime, you can use this workaround (it's far from elegant, but will work):
```
const ButtonUnsetFirst = styled("button", {
  all: "unset",
  '&&': { 
    height: "40px",
    border: "4px solid green"
  },
});
```

Here we use the `&&` trick to increase the specificity of all other declarations. 

Thanks!

**Comment by rafgraph** [comment] 2020-12-03 12:48
Thanks, I’m excited for the upcoming release!

**Comment by peduarte** [comment] 2021-02-12 18:12
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Closed** 2021-02-16 15:39 UTC
Labels: bug, fixed-in-beta
