### ISSUE TITLE
Current release breaks Jest + JSDOM testing

### ISSUE THREAD

**Issue by zschiller** [modulz/stitches#179] opened 2020-09-04 19:30 UTC
This is already fixed in `canary` but it isn't possible to create Jest tests for components that use Stitches right now because this change isn't released yet:

https://github.com/modulz/stitches/commit/3fe265d8e97accfdbc27734fec2bc2af03a1f74d#diff-9731eac31947a9ee3816b17a76ad0bad

`ownerNode` isn't implemented correctly in JSDOM, which means that the `__variables__` sheet isn't created and causes all tests to fail at [this line](https://github.com/modulz/stitches/blob/canary/packages/core/src/index.ts#L547).

**Comment by rubenmoya** [comment] 2020-09-04 19:44
Maybe I shouln't have closed the issue yet 😂 but yes, this is a duplicate of https://github.com/modulz/stitches/issues/137, it is working in `canary` and should (🤞) be released on Monday 💪

**Comment by peduarte** [comment] 2020-09-04 20:09
@zschiller You can try the canary release:
```bash
yarn @stitches/react@canary
```

**Comment by peduarte** [comment] 2020-09-07 14:20
This is fixed in `0.0.2` 

Thanks!

**Closed by peduarte** 2020-09-07 14:20 UTC
Labels: fixed@canary
