### ISSUE TITLE
[0.1.0-canary.12] Compound Variants not working as expected with conditions

### ISSUE THREAD

**Issue by loiacon** [modulz/stitches#432] opened 2021-02-21 22:30 UTC
# Bug report

## Describe the bug

When you have Compound Variants with `conditions` in all their variants, the compound variant will be applied but with the wrong rule.

## To Reproduce

https://codesandbox.io/s/stitches-conditions-ts-fidkp

In this example, we have `bg` and `color` variants and one compound variant. Even when the variant changes with the condition, the compound variant rule will remain.

## Expected behavior
When variant changes inside the condition, the compound variant rule needs to be removed.

## System information

- OS: macOS
- Version of Stitches: 0.1.0-canary.12
- Version of Node.js: 14.13.0

**Comment by apostolos** [comment] 2021-02-22 15:07
Duplicate of https://github.com/modulz/stitches/issues/386

**Comment by peduarte** [comment] 2021-02-22 19:18
@loiacon thanks so much for raising this 🙌

@apostolos Thanks for the heads up, saved me going through them later. Closing in favour of #368. ♥️

**Closed by peduarte** 2021-02-22 19:18 UTC
