### ISSUE TITLE
TypeScript error with a function prop

### ISSUE THREAD

**Issue by vladmoroz** [modulz/stitches#471] opened 2021-03-10 15:26 UTC
# Bug report

## Describe the bug

Creating a styled Stitches component may break TS handling function props correctly.

<img width="1090" alt="Screenshot 2021-03-10 at 17 22 01" src="https://user-images.githubusercontent.com/8441036/110652562-2852fd80-81c5-11eb-842d-5838e06de5a9.png">

<img width="1090" alt="Screenshot 2021-03-10 at 17 21 53" src="https://user-images.githubusercontent.com/8441036/110652558-2721d080-81c5-11eb-9f72-36aa334bf7ab.png">

## To Reproduce
https://codesandbox.io/s/vigorous-lake-d5nu0?file=/src/App.tsx

**Comment by hadihallak** [comment] 2021-03-11 10:59
Might be related to events getting implicit any as well which in this case might be a TS limitation

**Comment by peduarte** [comment] 2021-07-21 08:38
not able to reproduce: https://codesandbox.io/s/black-mountain-hbrj4?file=/src/App.tsx

PS: Seems the sandbox link in the description is for something else.

Closing, feel free to re-open, but I think this may have been an issue with canary.

**Closed by peduarte** 2021-07-21 08:38 UTC
Labels: typescript
