### ISSUE TITLE
Typescript error when extending from another base component

### ISSUE THREAD

**Issue by junagao** [modulz/stitches#854] opened 2021-10-22 11:55 UTC
# Bug report

## Describe the bug

I have a component that extends from a base component, example:
```js
const BaseText = styled("div", {
  fontSize: "$1",
  variants: {
    variant: {
      blueberry: {
        color: "$purple"
      }
    }
  }
});

const Text = styled(BaseText, {
  variants: {
    variant: {
      tomato: {
        color: "$tomato"
      }
    }
  }
});
```

```js
<Text variant="tomato">tomato</Text> // ok
<Text variant="blueberry">blueberry</Text> // typescript error
```
But when using the Text component with the variant in the BaseText, it returns the following Typescript error:
`No overload matches this call.`

<img width="1111" alt="Screenshot 2021-10-22 at 13 47 49" src="https://user-images.githubusercontent.com/615616/138448671-ac57e750-20d5-4efe-8fba-c8b34ee69af2.png">

Shouldn't variants from the base component be inherited? It seems to be a Typescript error because it gets rendered correctly.

## To Reproduce

1. Go to [https://codesandbox.io/s/crazy-mcnulty-kjjri](https://codesandbox.io/s/crazy-mcnulty-kjjri?file=/src/App.tsx:428-470)
2. Hover over variant in `<Text variant="blueberry">blueberry</Text>
3. See error

## Expected behavior

Don't display any Typescript error.

## System information

- Version of Stitches: 1.2.5

## Additional context

One workaround that made the error go away was adding an empty variant with the same name of the base component into the composed component:
```js
const Text = styled(BaseText, {
  variants: {
    variant: {
      blueberry: {}, // <----- variant from base component but empty
      tomato: {
        color: "$tomato"
      }
    }
  }
});
```

Is there another solution without having to replicate all the base variants like so?

**Comment by hadihallak** [comment] 2022-02-17 11:59
This is a duplicate of #749 which is now fixed under a canary release.
could you please upgrade to the latest canary`1.2.7-0` and test again?

**Closed by hadihallak** 2022-02-17 11:59 UTC
Labels: typescript, P1

**Comment by junagao** [comment] 2022-03-09 14:03
Hi @hadihallak, just tested it with the 1.2.7-0 and also 1.2.7 version but still not working. Check out the same codesandbox at: https://codesandbox.io/s/crazy-mcnulty-kjjri
