### ISSUE TITLE
Type error for userSelect key in styled()

### ISSUE THREAD

**Issue by tarngerine** [modulz/stitches#329] opened 2021-01-07 23:57 UTC
# Bug report

## Describe the bug

Given 
```
const styles = {
  userSelect: 'none'
}
const Button = styled("button", styles)
```

this throws a typeerror. as soon as i remove/comment out `userSelect: 'none'` the typeerror goes away. same error for any other value

## To Reproduce

See code above, run in a react app with typescript support

## Expected behavior

This should not have any typescript complaints. I can make up any random key and it doesn't complain

## Error message

Type error in VSCode

```
Argument of type '{ userSelect: string; }' is not assignable to parameter of type 'TComponentStylesObject<{ prefix: string; tokens: { colors: { $hyperlink: string; $green: string; $transparentBlack: string; $transparentWhite: string; $grey30: string; $transparentGrey30: string; $white80: string; ... 14 more ...; $linkBlue: string; }; ... 5 more ...; shadows: { ...; }; }; breakpoints: {}; utils: {}...'.
  Type '{ userSelect: string; }' is not assignable to type '{ [pseudo: string]: TFlatCSS<{ prefix: string; tokens: { colors: { $hyperlink: string; $green: string; $transparentBlack: string; $transparentWhite: string; $grey30: string; $transparentGrey30: string; $white80: string; ... 14 more ...; $linkBlue: string; }; ... 5 more ...; shadows: { ...; }; }; breakpoints: {}; uti...'.
    Type '{ userSelect: string; }' is not assignable to type '{ [pseudo: string]: TFlatCSS<{ prefix: string; tokens: { colors: { $hyperlink: string; $green: string; $transparentBlack: string; $transparentWhite: string; $grey30: string; $transparentGrey30: string; $white80: string; ... 14 more ...; $linkBlue: string; }; ... 5 more ...; shadows: { ...; }; }; breakpoints: {}; uti...'.
      Property 'userSelect' is incompatible with index signature.
        Type 'string' is not assignable to type 'TFlatCSS<{ prefix: string; tokens: { colors: { $hyperlink: string; $green: string; $transparentBlack: string; $transparentWhite: string; $grey30: string; $transparentGrey30: string; $white80: string; ... 14 more ...; $linkBlue: string; }; ... 5 more ...; shadows: { ...; }; }; breakpoints: {}; utils: {}; }> | ({ ...;...'.ts(2345)```

## System information

- OS: macOS
- Version of Stitches: 0.0.3-canary-4
- VSCode 1.52.1

**Comment by LexSwed** [comment] 2021-01-08 08:15
your `styles` object has type `{ userSelect: string }` which stitches doesn't like, inner types can't infer that `userSelect` is a CSS property and `'none'` is a respectful possible value of that property. But you can help yourself and stitches with helpers. I think some type helpers come in the next version of stitches, which will be available soon
For now, you can create those helpers yourself, something similar to
```ts
import type { TCss, TCssProperties } from '@stitches/core'

import type { css } from 'stitches.config'

// infer Stitches Config type from your stitches.config I'm sure this part can be done clearer
type GetConfig<S> = S extends TCss<infer T> ? T : never
interface Config extends GetConfig<typeof css> {}

// use this config to create type helpers
type StylesObject = TCssProperties<Config>

const styles: StylesObject = {
  userSelect: 'none',
}
```

**Comment by tarngerine** [comment] 2021-01-08 16:53
hmm im not sure i understand why `userSelect` specifically is not accepted, but something like 

```
{
  poop: "none"
}
```

is ok. user-select is part of the CSS spec, should it not be accepted?

thanks for the workaround, i managed to work around without too many lines by doing a destructured assignment for user-select: none inside styled()

```
const styles = {...}
const Button = styled('button', {...styles, userSelect: 'none'})

```

**Comment by tarngerine** [comment] 2021-01-08 16:54
(im a total typescript noob, sorry!)

**Comment by peduarte** [comment] 2021-01-08 21:18
It's because you've abstracted the `styles` and it doesnt contain the correct type. 

This is something we'll fix in the new versions of Stitches by exposing a CSS Type that you can import.

For now, you can type it as `any`:
```
const styles: any = {
  userSelect: 'none'
}
const Button = styled("button", styles)
```

or cast it as `any`:

```
const styles = {
  userSelect: 'none'
}
const Button = styled("button", styles as any)
```

**Comment by tarngerine** [comment] 2021-01-08 23:00
great to hear types will be provided in the future!

 i did try any casting first, but bc i have variants in the styles definition as well, it gave a type error when trying to set the attrs like <Button large={true}>

**Comment by blasterpistol** [comment] 2021-01-09 05:35
You can just mark the userSelect 'none' value as a literal type and not as a generic string
```tsx
const styles = {
  userSelect: 'none' as 'none'
}
const Button = styled("button", styles)
```

**Comment by peduarte** [comment] 2021-01-11 09:32
@tarngerine agh, yeah :/ sorry for that. the experience there will be improved very soon. thanks!

**Comment by peduarte** [comment] 2021-02-09 21:39
Closing as its a duplicate of https://github.com/modulz/stitches/issues/304

**Closed by peduarte** 2021-02-09 21:39 UTC
