### ISSUE TITLE
Incorrect typing for `css` prop on Canary

### ISSUE THREAD

**Issue by sandgraham** [modulz/stitches#715] opened 2021-08-10 05:30 UTC
# Bug report

## Describe the bug

On `1.0.0-canary.5` the `css` prop seems to evaluate to the `unknown` type on styled components.

## To Reproduce

Compare:

Canary: https://codesandbox.io/s/stitches-css-1-0-0-canary-5-zx1h0
0.2.4: https://codesandbox.io/s/stitches-css-0-2-4-3i864

## Expected behavior

The `css` prop should be typed.

_It looks like this started in `1.0.0-canary.4` as the version before it, `1.0.0-canary.3`, works as expected._

**Comment by peduarte** [comment] 2021-08-10 07:37
Thanks

**Comment by peduarte** [comment] 2021-08-10 07:37
@jonathantneal can we add a test for this please? looks like a regression

**Comment by jonathantneal** [comment] 2021-08-10 14:18
I would need help writing these tests. We do not have anything setup for testing expected types.

**Comment by jonathantneal** [comment] 2021-08-17 10:52
I’m no longer seeing this in canary-10. 🎉

@sandgraham, if you have time to confirm, please do. Otherwise, I think we can close this end-of-day.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/188426/129713474-c97ec3df-1f55-48df-a743-c3fe74641a98.png">
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/188426/129713547-608ee327-e164-41c8-8327-3da1d37e19b1.png">

**Comment by sandgraham** [comment] 2021-08-17 17:37
❤️ Can confirm this is fixed in 10 and 11. [Sandbox](https://codesandbox.io/s/stitches-css-1-0-0-canary-11-zfkpd?file=/src/App.tsx)

**Closed** 2021-08-23 08:03 UTC
Labels: typescript
