### ISSUE TITLE
Ability to use current theme variables inside utils

### ISSUE THREAD

**Issue by berkaey** [modulz/stitches#894] opened 2021-12-12 18:00 UTC
Hello, I'm trying to prepare some design system utils and I did come close to where the stitches end and workarounds start. :) 

Basically I need the current theme's props inside utils to achieve a proper way to manipulate a color.

The below example only works with the default theme. I need to put `" .dark &": {} ` on every component if I need to use this util. (or any other utils if the utils manipulate themed base properties like colors.)

```ts
 backroundWithOpacity: ([palette, opacity]: [
        `$${keyof typeof tokens.colors}`,
        `$${keyof typeof tokens.opacity}`,
      ]) => {
        if (!palette) return { background: undefined };

        const cleanKey = (key: string) => key.replace("$", "");

        const colorKey = cleanKey(palette) as keyof typeof tokens.colors;
        const color = hexToRgb(tokens.colors[colorKey]);
        const alphaKey = cleanKey(
          opacity,
        ) as unknown as keyof typeof tokens.opacity;
        const alpha = tokens.opacity[alphaKey];

        return {
          background: `rgba(${color.r},${color.g},${color.b}, ${alpha})`,
        };
      },
```

Usage: 
```ts
backroundWithOpacity: ["$fg", "$5"] // $fg is "#fff", but overwritten to "#000" if dark mode is preferred.
```

If I can reach the current tokens inside function it could just work. Like below;

``` ts
backroundWithOpacity: ([palette, opacity]: [
        `$${keyof typeof tokens.colors}`,
        `$${keyof typeof tokens.opacity}`,
      ],  config: Stitches.Config ) => {
        if (!palette) return { background: undefined };

       const tokens = config.theme

        const cleanKey = (key: string) => key.replace("$", "");

        const colorKey = cleanKey(palette) as keyof typeof tokens.colors;
        const color = hexToRgb(config tokens.colors[colorKey]);
        const alphaKey = cleanKey(
          opacity,
        ) as unknown as keyof typeof tokens.opacity;
        const alpha = tokens.opacity[alphaKey];

        return {
          background: `rgba(${color.r},${color.g},${color.b}, ${alpha})`,
        };
      },
```

**Comment by peduarte** [comment] 2021-12-13 10:57
interesting, is that because you're resolving the tokens to its actual value, rather than using the CSS Property? 

if you could create a repro I could then take a look. Cheers!

**Comment by peduarte** [comment] 2021-12-13 12:13
I see, i see, thinking...

i think we need a proper minimal reproduction for this, do you reckon you could put one together for us?

**Comment by berkaey** [comment] 2021-12-14 10:03
here you go, https://github.com/berkaey/stitches-feature-request-demo

Btw, not related to this but this implementation is suggested to handle "flash of light theme" but interestingly sometimes even the system is in dark mode, it just won't activate the dark theme.

**Closed** 2021-12-15 15:25 UTC
