### ISSUE TITLE
Negative token-aware values

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#78] opened 2020-08-10 08:02 UTC
We need to support negative token aware values for numerical scales, such as `space` and `size`.

Repro: https://codesandbox.io/s/stitches-negative-token-aware-values-ifun5?file=/src/App.tsx

**Comment by christianalfoni** [comment] 2020-08-17 17:41
Aha! This is actually impossible with Typescript. You can not dynamically add keys to an object and expect them to be typed. They have to be explicitly set. But would argue that it does not take much time adding the negatives by hand? Like its config, not something you would do often? 😄 

Or could expose a function for non Typescript users:

```ts
{
  tokens: {
    space: withNegatives({
      "1": "1rem"
    }) // { "-1": "-1rem", "1": "1rem" }
  }
}
```

**Comment by hadihallak** [comment] 2020-08-18 08:13
Good point @christianalfoni 

I don't mind both tbh. I think the only place where this would bug me is if I was modifying my scales.
maybe we could implement withNegativeValues internally so that js users who don't care about this could work on it without importing any functions

**Comment by peduarte** [comment] 2020-08-18 08:19
😓 😂 

Typescript users:
They'll understand why its not possible to dynamically add keys to the scale. If they want the autocomplete experience, they'll be happy to simply add a negative scale. Easy enough. Requires good documentation. 

Non-typescript users:
They'll probably expect negative values to _just work_. They wouldn't get autocomplete anyway, right? (maybe with intelisense?) But If we can make them work, I think that's what matters - even if there's no typing. 


Negative Function:
I think we can offer this as a helper. No harm doing so, and seems like a simple enough thing to implement. @christianalfoni and @hadihallak keep me same here in regards to effort please

CSS Calc:
This was a super common technique used back in SASS days. Every one seemed pretty happy with it... haha
```
margin: 'calc(2 * -1)'
```
☝️ where `2` is `space.2`. That would mean parsing the string, looking for tokens. I think some of this is already happening in #81 Again, @christianalfoni and @hadihallak please keep me sane.

**Comment by hadihallak** [comment] 2020-08-18 08:41
yeah the lookup isn't an issue, I think the issue is that we can't do this while also offering typescript-based autocomplete

**Comment by peduarte** [comment] 2020-08-18 08:48
Understood.

So to offer better TS lookups, there are 2 options:
- manually add negative scale
- use a `negative` function

Everything else still works, but without the lookups

**Comment by hadihallak** [comment] 2020-08-20 02:24
While working on moving this issue forward with Colm we uncovered two major issues:
- Numeric values already mean something in cssinjs libraries and react (5 === '5px'). So we have to respect that convention.
- Line-height supports unitless values, so we can't mess with that.

we're gonna rework how tokens get applied to CSS values so that tokens are required to have a prefix (TBD later during implementation) which in turn should simplify some of the parsing required for things like box-shadow but we'd lose some native typescript autocomplete so we'd need to handle that via plugins later.

**Comment by peduarte** [comment] 2020-08-20 06:57
>Numeric values already mean something in cssinjs libraries and react (5 === '5px'). 

I don't see what's the major issue with this. Is it that we don't convert unitless numbers to `px`? Can you explain?

**Comment by rubenmoya** [comment] 2020-08-27 13:40
Hello! I'm not sure in which version happened, but I was able to do:

```
space: {
  '-md': '-16px',
  '-sm': '-8px',
  '-xs': '-4px',
  xs: '4px',
  sm: '8px',
  md: '16px',
}
```

and now it doesn't work, it looks like extra `-` are removed from the keys when converted to CSS variables, it also happened with the colors, they used to be `blue-400` and now they appear as `blue500`.

Is this a bug? Or is intentional?

Right now I'm using `_` as a workaround but it looks pretty weird 😂

**Comment by hadihallak** [comment] 2020-08-27 22:26
@rubenmoya Thanks for reporting this. 
Yeah this is related to a change we did before to remove non-allowed characters from tokens names. look like the `-` is being removed there by a mistake.
negative breakpoints the way you defined them should work and will be handled as part of this issue.

**Closed** 2020-08-29 06:30 UTC
Labels: bug, priority: 1
