### ISSUE TITLE
Add support for inline media queries

### ISSUE THREAD

**Issue by jjenzz** [modulz/stitches#67] opened 2020-08-04 13:03 UTC
Currently consumers need to update the `screens` if they need a media query but there may be cases where a component needs a very specific implementation that is not shared anywhere else in the codebase. How can we design the API to allow for inline media query definitions?

```jsx
const Thing = styled('div', {
  color: 'red',

  '@media(min-width: 300px)': {
    // inline media query
  }
});
```

**Comment by christianalfoni** [comment] 2020-08-09 08:44
I am not sure if this is a good idea. The reason is that you can not guarantee specificity this way. Cause these media queries will be injected into the "common" stylesheet and then you might get into unexpected behaviour. 

If you rather force the users to create `screens` in the config, they are forced to think specificity by the order of how they are defined. 

The only way to guarantee specificity is handled here is to resolve the inline media query into its own stylesheet and evaluate its values. So for example `min-width: 300px` will be injected before `min-width: 600px`. But this is extremely tricky. So yeah... it is a tricky one.

Here is an example of how the problem occurs:
https://codesandbox.io/s/stoic-cray-ioipl?file=/src/styles.css

Maybe some other way to handle it, but yeah, this is the challenge 😄

**Comment by peduarte** [comment] 2020-08-10 06:50
@christianalfoni thanks for your input. I clearly see the challenge here 👍 

We'd like to guide users to define their media queries, but we don't feel comfortable with not supporting inline ones. Sometimes things cant be rationalised, and defining an inline media queries removes that barrier to having to give it a name, etc.

Im excited to see what we can come up with though 😃 

@hadihallak any ideas?

**Comment by hadihallak** [comment] 2020-08-10 19:47
yeah. this is indeed a tricky one. overall I would be wary about anything that is linked to insertion order as this kinda stuff gets even trickier with variants and lazily injecting them 🤔

**Comment by peduarte** [comment] 2020-08-13 10:19
I think we need to get this implemented in the most simple way, and then we can build some demos and see if we're having the specificity issues mentioned above

From a theoretical point of view, I share the same concerns, but without being able to reproduce it Im not sure how realistic they are

**Comment by christianalfoni** [comment] 2020-08-14 08:08
This is implemented in https://github.com/modulz/stitches/commit/c5fbeac0872010e21ff2af37f7ee4b7ce3c4de97, with some updates on later commits

**Comment by peduarte** [comment] 2020-08-18 07:50
Closing this in favour of #86

**Closed by peduarte** 2020-08-18 07:50 UTC
Labels: feature, priority: 1
