### ISSUE TITLE
Composing works wrong with nextjs

### ISSUE THREAD

**Issue by sidletski** [modulz/stitches#778] opened 2021-09-12 16:55 UTC
# Bug report

## Describe the bug
Styles of composed components are declared before the styles of the components they are based on.

## To Reproduce
You can learn more about the bug at the [sandbox](https://codesandbox.io/s/stitches-and-next-themes-forked-0ezqm?file=/pages/index.js). In theory, the padding of the button should be equal to 15px, but it is equal to 10px, because styles of the HeaderButton component for some reason are declared before styles of the Button component on which it is based. If you try to change the padding from 15px to another in realtime and save the file, all HeaderButton styles will be written after the Button and the styles will work as they should.

## Expected behavior
Styles of components that are based on others should be declared strictly after them.

## System information

- Version of Stitches: [e.g. 1.1.0]

**Comment by sidletski** [comment] 2021-09-12 17:08
Same behavior even when using className: [here](https://codesandbox.io/s/stitches-and-next-themes-forked-mdk6x?file=/components/Header.js)

**Comment by peduarte** [comment] 2021-09-13 15:11
Hi there! Thanks for your issue.  This is actually by design 🥲 

From what I can tell, you're wanting to pass overrides to a Stitches React Component. You can do this in two ways:

**Approach #1**
_[Override styles](https://stitches.dev/docs/overriding-styles) via the `css` prop.

```jsx
const Button = styled('button', { ...yourStyles })

() => <Button css={{ ...yourOverrides }} />
```

**Approach #2**
_[Compose components](https://stitches.dev/docs/composing-components)_ via the `styled` function.

```jsx
const Button = styled('button', { ...yourStyles })
const HeaderButton = styled(Button, { ...yourOverrides })

() => <HeaderButton />
```

Conclusion: Mixing Stitches React Components with Stitches CSS Components will lead to unexpected results - as you've discovered. This is because the styles for Stitches Styled Components are injected later in the stylesheet, by design.

**Comment by sidletski** [comment] 2021-09-14 12:24
Thanks for your response!
Now I understand the design when using css and styled, but as for the composing using styled there is still an error. [Here](https://codesandbox.io/s/stitches-and-next-themes-forked-0ezqm?file=/pages/index.js) I'm only using a **styled** function and composition is not working properly (padding should be 15px instead of 10px)

**Comment by peduarte** [comment] 2021-09-14 13:39
Ah, yeah. That's a bug, it's being tracked here: https://github.com/modulz/stitches/issues/671
The bug is related to calling `styled` with a React Component, and not with a Stitches Component. 

If possible, use the `css` prop to pass overrides, that will definitely work. 

Sorry 😢 But we'll fix it soon!

If you don't have any more questions, would you please close this issue, in favour of 671? 

Thanks!

**Closed** 2021-09-14 14:00 UTC
