### ISSUE TITLE
Feature request: Support for preact/compat

### ISSUE THREAD

**Issue by loiacon** [modulz/stitches#454] opened 2021-03-04 19:15 UTC
**Is your feature request related to a problem? Please describe.**
If we try to use `preact/compat` with `@stitches/react` it throws an error:
```
DOMException: Failed to execute 'createElement' on 'Document':
The tag name provided ('.sxp3sgw') is not a valid name.
```

**Describe the solution you'd like**
Just work out of the box 📦, as other tools do

**Comment by peduarte** [comment] 2021-03-04 20:10
We are working on a "stitches/preact" package as well. The react one won't just work with preact because it has some react-specific behaviours for ref forwarding. 

OOC what do you mean "other libraries do"? Does styled components or emotion work with preact out of the box?

**Comment by loiacon** [comment] 2021-03-04 21:40
Styled Components works without problems using `preact/compat` as alias for `react`.

I created a demo with NextJS + preact/compat + styled-components & stitches for comparison:
https://codesandbox.io/s/nextjs-preact-styled-components-s6ngt

**Comment by peduarte** [comment] 2021-03-04 21:50
Hmm, interesting, I wonder how they're able to to forward ref and still be compatible with Preact 🤔 /cc @jonathantneal

**Comment by jonathantneal** [comment] 2021-03-05 18:19
I am going to look into the issue further, to see what the cause is, and if it is indeed related to `forwardRef`. If that’s the case, then I can understand the appeal to release a Preact version.

Fun fact: before `forwardRef` was introduced to support polymorphism in React, Stitches worked with Preact out of the box, without even the need for `preact/compat`.

**Comment by vitordino** [comment] 2021-03-19 12:58
it worked out of the box (and incredibly great) on `0.0.3-canary.4`, just tested upgrading to `0.1.0-canary.20` and it stopped working.

**Comment by ch99q** [comment] 2021-04-28 10:18
To my understanding, it may be caused by the creation of an element through `Object.setPrototypeOf` and not `React.createElement` as seen in https://github.com/modulz/stitches/blob/canary/packages/react/src/index.js#L22.

Normally this function would be replaced with Preact's `createElement` but since Stitches just create the result of the ?`createElement` from React, it's only possible to use React and not Preact.

**Comment by jonathantneal** [comment] 2021-04-28 14:45
Yes. At first, the beta of this library used a regular object to work with React and Preact out-of-the-box, without any compat. However, supporting polymorphism correctly required `React.createRef`, while the change that made it in only upgraded the object `$$typeof` of the object.

In a future release, it may be better to switch to `React.createRef`, since cross-compatibility out-of-the-box is no longer an option.

**Comment by rafgraph** [comment] 2021-04-28 16:30
#580 might help with this, see [comment on using `React.createElement`](https://github.com/modulz/stitches/pull/580#discussion_r619232551), and [comment on using `React.forwardRef`](https://github.com/modulz/stitches/pull/580#discussion_r619653381).

Also, I think you might mean `React.fowardRef` not `React.createRef` (`createRef` just returns "an immutable object with a single mutable value" [source code](https://github.com/facebook/react/blob/master/packages/react/src/ReactCreateRef.js))

**Comment by jonathantneal** [comment] 2021-08-31 20:48
> In a future release, it may be better to switch to React.createRef, since cross-compatibility out-of-the-box is no longer an option.

We did make this change in the v0.2.x release, and this change remains in the v1 release, so I will close this. If there is a regression, tho, please do report it!

**Closed by jonathantneal** 2021-08-31 20:48 UTC

**Comment by airtonix** [comment] 2023-04-05 07:57
New to preact ( using it in Deno with Fresh ). 

Did I miss where this gotcha/papercut was mentioned on the stitches website? 

![image](https://user-images.githubusercontent.com/61225/230018118-9c41c895-2875-46ed-93fa-2b3298b47195.png)

[Screencast from 2023-04-05 17-29-30.webm](https://user-images.githubusercontent.com/61225/230018555-987b7490-0bab-4919-bbd5-15ebc395b344.webm)

Or am I forced to use `@stitches/core` ?

**Comment by ch99q** [comment] 2023-04-05 12:25
This PR is relatively old now, I'm using stitches core with Preach/Fresh 😅
