### ISSUE TITLE
Polymorphism lost when using StitchesProps 

### ISSUE THREAD

**Issue by dsbrianwebster** [modulz/stitches#307] opened 2020-11-07 14:28 UTC
# Bug report

## Describe the bug

The new `StitchesProps` helper is great for combining types or passing stitches props to a React.FC as a way to set default props without the deprecated `defaultProps`. However, in these use cases, the `as` prop loses its polymorphic ability and only accepts the element defined in `styled()` or undefined.

## To Reproduce

1. version 0.0.3-canary.4
2. Example component `Heading.tsx`

```jsx
export const StyledHeading = styled('h2', {
  margin: '0',

  variants: {
    size: {
      '1': {
        fontSize: '$1',
      },
      '2': {
        fontSize: '$2',
      },
    },
  },
})


export const Heading: React.FC<HeadingProps> = ({ size = "1", children, ...props }) => {
  return (
    <StyledHeading size={size} {...props}>
      {children}
    </StyledHeading>
  )
}

export type HeadingProps = StitchesProps<typeof StyledHeading>

```

3. Try using <Heading /> with an `as` prop, example:

```jsx
<Heading as="h1" size="1">Heading 1</Heading>
```

Type '"h1"' is not assignable to type '"h2" | undefined'.ts(2322)

## Expected behavior

As should be `as?: React.ElementType` or something that retains its polymorphism

## Screenshots

![image](https://user-images.githubusercontent.com/8154653/98443618-64bd0280-20da-11eb-82d8-fe6a3a13893b.png)

## System information

- OS: [e.g. macOS]
- Version of Stitches: [e.g. 0.0.3-canary.4]
- Version of Node.js: [e.g. 12.16.3]

**Comment by peduarte** [comment] 2020-11-09 09:37
@dsbrianwebster thanks for raising this. I can validate this is indeed happening: https://codesandbox.io/s/stupefied-varahamihira-mpy2o?file=/src/App.tsx

We're currently working on a bunch of Typescript improvements here: #294 

/cc @hadihallak

**Comment by dsbrianwebster** [comment] 2020-11-09 14:04
Amazing @peduarte. Can't tell just you how much we've been loving stitches! 🎉 👏  
We currently have a couple production projects getting converted right now, I'll let you know if we encounter anything else.

**Comment by peduarte** [comment] 2020-11-09 14:51
@dsbrianwebster thanks so much <3

**Comment by hadihallak** [comment] 2020-11-14 05:32
IIRC, this isn't working by design because by inferring the props we lose the overloaded call signature we use to conditionally type the `as` prop.
I'd be happy to give this another look if a similar utility existed for other cssinjs libraries and it retained polymorphism 

However, I think we could introduce a new type that is meant to mimic `React.FC` but with the addition of polymorphism

**Comment by dsbrianwebster** [comment] 2020-11-14 14:07
@hadihallak makes total sense. The new type solution is interesting. Something like 

`import { StitchesPolymorphicComponent } from @stitches/react` or `import { StitchesPolymorphicProps } from @stitches/react` I imagine?

As we have been experimenting with stitches and building a component library we actually encounter this need rather frequently either when setting defaults, or when the component requires a bit more than just the single stitches tag like a fancy button ;)

Going with the button example, obviously `<button as=”a”>Text</button>` or `<button as={Link}>Text</button>` comes up. Since we are passing that `as` prop to our `<StyledButton>` stitches component inside our `React.FC` It *does* receive it and we *do* get the polymorphic behavior (Button renders as `a` or `Link`), but we just get the type errors which we `@ts-ignore` as of now. I feel like more often than not, especially since the as prop will ultimately be passed through, I’d would find myself favoring whatever type or method (ie. StitchesPolymorphicComponent, or StitchesPolymorphicProps) made ts happy.

**Comment by hadihallak** [comment] 2021-02-10 04:05
@peduarte I think we should close this issue and create a new one for a StitchesPolymorphicComponent or just forward people to using our radix polymorphism package as this issue can't be fixed with `StitchesProps`

**Comment by peduarte** [comment] 2021-02-10 08:16
@hadihallak yeah, makes sense. Lets keep it open until we have this working and documented.

**Comment by peduarte** [comment] 2021-02-16 15:50
Closing as StitchesProps has been removed from beta canary. 

When you wrap a Stitches Component around your own component, you lose polymorphism, thats just how it works unfortunately. Its a pain. 

We do that for our DS, using the Radix polymorphic package. Its not documented yet, but you can look here to see how we do it: https://github.com/radix-ui/design-system/blob/master/components/Button.tsx#L203-L207

alternatively you can use https://github.com/kripod/react-polymorphic-box

**Closed by peduarte** 2021-02-16 15:50 UTC
Labels: beta, typescript
